#! /bin/sh
# internal utility for putting random keys into sample configuration file
# Copyright (C) 1998, 1999  Henry Spencer.
# 
# This program is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the
# Free Software Foundation; either version 2 of the License, or (at your
# option) any later version.  See <http://www.fsf.org/copyleft/gpl.txt>.
# 
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
# or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
# for more details.
#
# RCSID $Id: //WIFI_SOC/MP/SDK_4_3_0_0/RT288x_SDK/source/user/openswan-2.6.22/programs/_confread/randomize#1 $

awk '/`[0-9]+`/ {
	match($0, /`[0-9]+`/)
	n = substr($0, RSTART+1, RLENGTH-2)
	cmd = "./ranbits --quick " n
	cmd | getline key
	cmd | getline eof
	close(cmd)
	sub(/`[0-9]+`/, key, $0)
	print
	next
}
{ print }' $*
