# Makefile for simpleca programs
# Copyright (C) 2004	Michael Richardson <mcr@xelerance.com>
# 
# This program has a GPL compatible license.
#
# RCSID $Id: //WIFI_SOC/MP/SDK_4_3_0_0/RT288x_SDK/source/user/openswan-2.4.9/programs/simpleca/Makefile#1 $

OPENSWANSRCDIR?=$(shell cd ../..; pwd)
include ${OPENSWANSRCDIR}/Makefile.inc

PROGRAM=simpleca
EXTRA5PROC=${PROGRAM}.5

include ${srcdir}../Makefile.program

#
# $Log: Makefile,v $
# Revision 1.2  2004/12/18 18:13:43  mcr
# 	adjusted Makefiles so that ${OBJDIR} builds work.
#
# Revision 1.1  2004/06/17 02:03:27  mcr
#    makefile for simpleca (not yet committed itself)
#
#
#
